config/routes.rb
BikeShop::Application.routes.draw do

  
  root 'bicycle_orders#index'

  resources :bicycle_orders

  

end

app/models/bicycle_order.rb
class BicycleOrder < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :wheel_set
end

app/models/wheel_set.rb
class WheelSet < ActiveRecord::Base
  validates :name, presence: true

  has_many :bicycle_orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bicycle_orders_controller.rb
class BicycleOrdersController < ApplicationController

  def index 
    @bicycle_orders = BicycleOrder.all
    # @wheel_sets = WheelSet.all
  end

  def new
    @bicycle_order = BicycleOrder.new
  end

  def edit
    @bicycle_order = BicycleOrder.find(params[:id])
    @wheel_sets = WheelSet.all
  end

  def show 
  end


  def update
    bicycle_order = BicycleOrder.find(params[:id])

    if bicycle_order.update(bicycle_order_params)
      redirect_to edit_bicycle_order_path(bicycle_order)
    else
      redirect_to edit_bicycle_order_path(bicycle_order)
    end
  end

  def create
    bicycle_order = BicycleOrder.new(bicycle_order_params)

    if bicycle_order.save
      redirect_to edit_bicycle_order_path(bicycle_order)
    else
      redirect_to new_bicycle_order_path
    end
  end

  def index 
    @bicycle_orders = BicycleOrder.all
    @wheel_sets = WheelSet.all
  end


  def bicycle_order_params
    params.require('bicycle_order').permit('name', 'wheel_set_id')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bicycle_orders/edit.html.erb
<h1>Edit Bicycle</h1>

<%= form_for @bicycle_order do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :wheel_set %>
    <%= f.select :wheel_set_id, @wheel_sets.map { |wheel_set| [wheel_set.name, wheel_set.id] }, include_blank: 'Default' %>
  </div>

  <%= f.submit %>
<% end %>

app/views/bicycle_orders/index.html.erb
<h2>This is the index page</h2>

<% @bicycle_orders.each do |f| %>
	<div class="module">	  	
	    <p><%= link_to f.name, edit_bicycle_order_path(f.id) %></p> 
	    <p><%= f.wheel_set.name%></p> 
	    
	  </div>
<% end %>	
<!-- <p><%= @wheel_sets%></p>  -->

<div class="content">
	
</div>

app/views/bicycle_orders/new.html.erb
<h1>New Order</h1>

<%= form_for @bicycle_order do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BikeShop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<%= link_to "List of Orders", bicycle_orders_path , class: "tabs" %>
		<%= link_to "New Order", new_bicycle_order_path , class: "tabs" %>

<%= yield %>

</body>
</html>